In [12]:
import numpy as np
arr1 = np.array([[20,15],
                 [45,10]])
print(arr1.dtype)
print(arr1.ndim)
print(arr1.shape)
print(arr1.flatten())
arr2 = np.array([[61,23],[14,57]])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1/arr2)

int32
2
(2, 2)
[20 15 45 10]
[[81 38]
 [59 67]]
[[-41  -8]
 [ 31 -47]]
[[0.32786885 0.65217391]
 [3.21428571 0.1754386 ]]
