In [1]:
import numpy as np
arr3 = np.array([[25,54,58],
                 [21,75,96],
                 [56,25,36]])
print(arr3.transpose())
arr4 = np.array([[45,12,78],
                [45,85,65],
                [25,43,67]])
print(arr3.dot(arr4))

[[25 21 56]
 [54 75 25]
 [58 96 36]]
[[ 5005  7384  9346]
 [ 6720 10755 12945]
 [ 4545  4345  8405]]
